### ISSUE TITLE
Formatter file does not contain the required functions.

### ISSUE THREAD

**Issue by khyeborg** [Ovsyanka83/autograder#47]
Hi, I am experiencing the Formatter file does not contain the required functions error for Python. I ran the autograder command on the Python example provided and got this error.

**Comment by Ovsyanka83** [comment]
We have changed the formatting model yesterday which is why you ran into problems. I just released the new version on PyPI. Run `pip3 install --upgrade --no-cache-dir assignment-autograder` to upgrade to a new version (2.11.1).

Check back here if it fixes your problem!

**Comment by khyeborg** [comment]
Hi, yes, I'm not receiving the Formatter file does not contain the required functions error anymore. But the program throws an error in other ways. Looking forward to the easy-to-use graphical user interface you plan to implement!

**Comment by Ovsyanka83** [comment]
Okay. Closing this issue, then. Feel free to open any others and describe the errors you get. I will happily assist.
